version: '2'

.catalog:
  name: Home Assistant
  description: |
    Track and control all devices at home and automate control.
  version: 0.68.1
  questions:
   - variable: 'HA_PORT'
     description: 'Home Assistant Port'
     label: 'Home Assistant Port'
     required: true
     type: 'int'
     default: 8123
    - variable: "db_link"
      description: |
        DB external service link cluster.
      label: "External db service"
      default: ""
      required: false
      type: "service"
    - variable: "MYSQL_DATABASE"
      description: "mysql db"
      label: "Mysql db"
      required: true
      default: "homeassistant"
      type: "string"
    - variable: 'MYSQL_USER'
      description: "mysql user"
      label: "Mysql User"
      required: true
      default: "homeassistant"
      type: "string"
    - variable: "MYSQL_PASSWORD"
      description: 'MySQL Password'
      label: 'MySQL Password'
      required: true
      type: 'password'
    - variable: 'MYSQL_ROOT_PASSWORD'
      description: "mysql root password"
      label: "Mysql Password"
      required: true
      default: "default_pass"
      type: "password"
    - variable: 'MYSQL_PORT'
      description: 'MySQL Port'
      label: 'Leave empty for not exposing MySQL'
      required: false
      type: 'int'
      default: 3306
   - variable: 'TZ'
     description: 'Timezone (eg. Europe/Amsterdam)'
     label: 'Timezone'
     required: true
     type: 'string'
     default: 'Europe/Amsterdam'
   - variable: 'DEV_ZWAVE'
     description: 'Device ID (/dev/serial/by-id/), leave empty for no ZWave device'
     label: 'ZWave device'
     required: false
     type: 'string'
     default: 'usb-0658_0200-if00'
   - variable: 'DEV_RFXCOM'
     description: 'Device ID (/dev/serial/by-id/), leave empty for no RFXCOM device'
     label: 'RFXCOM device'
     required: false
     type: 'string'
     default: 'usb-RFXCOM_RFXtrx433_A1WP56WY-if00-port0'
services:
  homeassistant:
    scale: 1
    retain_ip: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 8123
      unhealthy_threshold: 3
      initializing_timeout: 300000
      interval: 2000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 120000
  mysql:
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 3306
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: home_assistant
        source_port: ${HA_PORT}
        target_port: 8123
      - priority: 2
        protocol: tcp
        service: mysql
        source_port: ${MYSQL_PORT}
        target_port: 22
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
